### ISSUE TITLE
How do I add it on Android for a non-dedicated server? And also what version do I need, I have version 1.4.155

### ISSUE THREAD

**Issue by Juandavidart** [Mikahael/PCModderServerFIles-FINAL#3]
I have done some steps that are the following: download the project in .zip, go to data and then copy everything that is in the scripts folder to /emulated/0/Bombsquad/sys/1.4 155/ and then the game does not open the game Or I think I log in normally and the mod doesn't even appear in the game :( Any solution?

**Comment by Juandavidart** [comment]
Mmm also if you could give me a version that the script works on Android and PC

**Comment by Mikahael** [comment]
> Mmm also if you could give me a version that the script works on Android and PC

The script should work, just replace the scripts folder with ur folder, and make sure an internet connection is there.

**Comment by Mikahael** [comment]
> > Mmm also if you could give me a version that the script works on Android and PC
> 
> The script should work, just replace the scripts folder with ur folder, and make sure an internet connection is there. 

You do need to have bombsquad 1.4.155 installed on your setup for it to work, if not, give me a holler and I'll look at it.

**Comment by Juandavidart** [comment]
> > Mmm tambien si me pudieran pasar una version que el script funcione en Android y PC
> 
> El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.

Hmm I did the following Download the file from the repository then go in and extract the scripts folder to /emulated/0/BombSquad/sys/1.4 155/
And the scripts folder was left in the 1.4 155 folder but it hasn't worked:( or something else is that I haven't understood if it is possible, explain to me how to do the installation because I watched the ByAng3l video for Install file server on Android

**Comment by Mikahael** [comment]
> > > Mmm tambien si me pudieran pasar una version que el script funcione en Android y PC
> > 
> > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> 
> Hmm I did the following Download the file from the repository then go in and extract the scripts folder to /emulated/0/BombSquad/sys/1.4 155/
> And the scripts folder was left in the 1.4 155 folder but it hasn't worked:( or something else is that I haven't understood if it is possible, explain to me how to do the installation because I watched the ByAng3l video for Install file server on Android 

Let me try on windows and see if it works, it should work, then I'll work on Android.

**Comment by Juandavidart** [comment]
> > > > Mmm también si me podría pasar una versión que el script funcione en Android y PC
> > > 
> > > 
> > > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> > 
> > 
> > Hmm hice lo siguiente Descargue el archivo del repositorio luego entre y extraiga la carpeta de scripts a /emulated/0/BombSquad/sys/1.4 155/ 
> > Y la carpeta de scripts quedo en la carpeta 1.4 155 pero no ha funcionado :( o algo mas es que no he entendido si es posible, expliquenme como hacer la instalacion porque vi el video de ByAng3l para Instalar servidor de archivos en Android
> 
> Déjame probar en Windows y ver si funciona, debería funcionar, luego trabajaré en Android.

Come on, okay, I'll wait for you. :D

**Comment by Mikahael** [comment]
> > > > > Mmm también si me podría pasar una versión que el script funcione en Android y PC
> > > > 
> > > > 
> > > > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> > > 
> > > 
> > > Hmm hice lo siguiente Descargue el archivo del repositorio luego entre y extraiga la carpeta de scripts a /emulated/0/BombSquad/sys/1.4 155/
> > > Y la carpeta de scripts quedo en la carpeta 1.4 155 pero no ha funcionado :( o algo mas es que no he entendido si es posible, expliquenme como hacer la instalacion porque vi el video de ByAng3l para Instalar servidor de archivos en Android
> > 
> > 
> > Déjame probar en Windows y ver si funciona, debería funcionar, luego trabajaré en Android.
> 
> Come on, okay, I'll wait for you. :D

boss, i tested it for windows, and its working just fine, Ill try a test for android soon.

**Comment by Juandavidart** [comment]
> > > > > > Mmm también si me podría pasar una versión que el script funcione en Android y PC
> > > > > 
> > > > > 
> > > > > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> > > > 
> > > > 
> > > > Hmm hice lo siguiente Descargue el archivo del repositorio luego entre y extraiga la carpeta de scripts a /emulated/0/BombSquad/sys/1.4 155/
> > > > Y la carpeta de scripts quedo en la carpeta 1.4 155 pero no ha funcionado :( o algo mas es que no he entendido si es posible, expliquenme como hacer la instalacion porque vi el video de ByAng3l para Instalar servidor de archivos en Android
> > > 
> > > 
> > > Déjame probar en Windows y ver si funciona, debería funcionar, luego trabajaré en Android.
> > 
> > 
> > Come on, okay, I'll wait for you. :D
> 
> boss, i tested it for windows, and its working just fine, Ill try a test for android soon.

Well I'll wait for the test, thanks for your answer :'D

**Comment by Mikahael** [comment]
> > > > > > > Mmm también si me podría pasar una versión que el script funcione en Android y PC
> > > > > > 
> > > > > > 
> > > > > > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> > > > > 
> > > > > 
> > > > > Hmm hice lo siguiente Descargue el archivo del repositorio luego entre y extraiga la carpeta de scripts a /emulated/0/BombSquad/sys/1.4 155/
> > > > > Y la carpeta de scripts quedo en la carpeta 1.4 155 pero no ha funcionado :( o algo mas es que no he entendido si es posible, expliquenme como hacer la instalacion porque vi el video de ByAng3l para Instalar servidor de archivos en Android
> > > > 
> > > > 
> > > > Déjame probar en Windows y ver si funciona, debería funcionar, luego trabajaré en Android.
> > > 
> > > 
> > > Come on, okay, I'll wait for you. :D
> > 
> > 
> > boss, i tested it for windows, and its working just fine, Ill try a test for android soon.
> 
> Well I'll wait for the test, thanks for your answer :'D

I have been testing on android,  I need some help, is there anyway I can contact you? do you have discord?

**Comment by Mikahael** [comment]
> > > > > > > Mmm también si me podría pasar una versión que el script funcione en Android y PC
> > > > > > 
> > > > > > 
> > > > > > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> > > > > 
> > > > > 
> > > > > Hmm hice lo siguiente Descargue el archivo del repositorio luego entre y extraiga la carpeta de scripts a /emulated/0/BombSquad/sys/1.4 155/
> > > > > Y la carpeta de scripts quedo en la carpeta 1.4 155 pero no ha funcionado :( o algo mas es que no he entendido si es posible, expliquenme como hacer la instalacion porque vi el video de ByAng3l para Instalar servidor de archivos en Android
> > > > 
> > > > 
> > > > Déjame probar en Windows y ver si funciona, debería funcionar, luego trabajaré en Android.
> > > 
> > > 
> > > Come on, okay, I'll wait for you. :D
> > 
> > 
> > boss, i tested it for windows, and its working just fine, Ill try a test for android soon.
> 
> Well I'll wait for the test, thanks for your answer :'D

My friend, the error has been resolved, the files will now work on android as well.

**Comment by Juandavidart** [comment]
> > > > > > > > Mmm también si me podría pasar una versión que el script funcione en Android y PC
> > > > > > > 
> > > > > > > 
> > > > > > > El script debería funcionar, simplemente reemplace la carpeta de scripts con su carpeta y asegúrese de que haya una conexión a Internet.
> > > > > > 
> > > > > > 
> > > > > > Hmm, hice lo siguiente. Descargue el archivo del repositorio luego entre y extraiga la carpeta de scripts a /emulated/0/BombSquad/sys/1.4 155/ 
> > > > > > Y la carpeta de scripts quedo en la carpeta 1.4 155 pero no ha funcionado :( o algo más es que no he entendido si es posible, expliquenme como hacer la instalacion porque vi el video de ByAng3l para Instalar servidor de archivos en Android
> > > > > 
> > > > > 
> > > > > Déjame probar en Windows y ver si funciona, debería funcionar, luego trabajaré en Android.
> > > > 
> > > > 
> > > > Vamos, vale, te espero. :D
> > > 
> > > 
> > > Jefe, lo probé para Windows y funciona bien. Pronto intentaré hacer una prueba para Android.
> > 
> > 
> > Bueno esperaré el examen, gracias por tu respuesta :'D
> 
> Amigo, el error ha sido resuelto, los archivos ahora funcionarán también en Android.

Thank you very much brother 🫂! thanks for solving the problem :'D

**Comment by Juandavidart** [comment]
Thank you very much for solving the problem :D
