### ISSUE TITLE
Well this is not just a problem Just a question 

### ISSUE THREAD

**Issue by Juandavidart** [Mikahael/PCModderServerFIles-FINAL#4]
Did you add that the maps look dark and with disco lights? 

How in the contributor video ByAng3l 

The mod works perfectly on PC and Android :D

**Comment by Mikahael** [comment]
> Did you add that the maps look dark and with disco lights? 
> 
> How in the contributor video ByAng3l 
> 
> The mod works perfectly on PC and Android :D

Disco Lights are still present, but I removed dark maps. To use discolights, check the command you need to use. Look at the command list pdf to see which cmd is available.

**Comment by Juandavidart** [comment]
> > ¿Agregaste que los mapas se ven oscuros y con luces de discoteca?
> > Cómo en el video del colaborador ByAng3l
> > El mod funciona perfectamente en PC y Android :D
> 
> Las luces de discoteca siguen presentes, pero he eliminado los mapas oscuros. Para usar luces de discoteca, consulta el comando que debes usar. Mira el PDF de la lista de comandos para ver qué comando está disponible.

Hmm and how can I use the dark maps but they are deleted?

One question and why are the characters no longer unlocked with the mod?

**Comment by Mikahael** [comment]
> > > ¿Agregaste que los mapas se ven oscuros y con luces de discoteca?
> > > Cómo en el video del colaborador ByAng3l
> > > El mod funciona perfectamente en PC y Android :D
> > 
> > Las luces de discoteca siguen presentes, pero he eliminado los mapas oscuros. Para usar luces de discoteca, consulta el comando que debes usar. Mira el PDF de la lista de comandos para ver qué comando está disponible.
> 
> Hmm and how can I use the dark maps but they are deleted?
> 
> One question and why are the characters no longer unlocked with the mod? 

Should be unlocked

**Comment by Juandavidart** [comment]
> > > > ¿Agregaste que los mapas se ven oscuros y con luces de discoteca? 
> > > > Cómo en el video del colaborador ByAng3l 
> > > > El mod funciona perfectamente en PC y Android :D
> > > 
> > > 
> > > Las luces de la discoteca siguen presentes, pero eliminó los mapas oscuros. Para usar luces de discoteca, consulta el comando que debes usar. Mira el PDF de la lista de comandos para ver qué comando está disponible.
> > 
> > 
> > Hmm y como puedo usar los mapas oscuros pero estan eliminados?
> > Una pregunta y porque ya no se desbloquean los personajes con el mod?
> 
> Debería estar desbloqueado

And if not, what can I do, sorry for the inconvenience. :(
